name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore --configuration Release

      - name: Execute unit tests
        run: dotnet test SuperDinner.UnitTests --no-build --configuration Release --verbosity normal

      - name: Execute integration tests
        run: dotnet test SuperDinner.IntegrationTests --no-build --configuration Release --verbosity normal
